/*
 * Copyright (C) 2018 Velocity Contributors
 *
 * The Velocity API is licensed under the terms of the MIT License. For more details,
 * reference the LICENSE file in the api top-level directory.
 */

package com.velocitypowered.api.event.player;

import com.velocitypowered.api.event.Event;
import com.velocitypowered.api.proxy.connection.InboundConnection;
import com.velocitypowered.api.proxy.player.java.JavaPlayerIdentity;
import org.checkerframework.checker.nullness.qual.Nullable;

/**
 * This event is fired after the {@link PreLoginEventImpl} in order to set up the game profile for
 * the user. This can be used to configure a custom profile for a user, i.e. skin replacement.
 */
public interface GameProfileRequestEvent extends Event {

  InboundConnection connection();

  String username();

  JavaPlayerIdentity initialProfile();

  boolean isOnlineMode();

  /**
   * Returns the game profile that will be used to initialize the connection with. Should no profile
   * be currently specified, the one generated by the proxy (for offline mode) or retrieved from the
   * Mojang session servers (for online mode) will be returned instead.
   *
   * @return the user's {@link JavaPlayerIdentity}
   */
  JavaPlayerIdentity gameProfile();

  /**
   * Sets the game profile to use for this connection.
   *
   * @param javaPlayerIdentity the profile for this connection, {@code null} uses the original profile
   */
  void setGameProfile(@Nullable JavaPlayerIdentity javaPlayerIdentity);
}
